modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
issueTrackerURL="https://github.com/starforcraft/Cable-Tiers/issues/new/choose"
[[mods]]
modId="cabletiers"
version="${file.jarVersion}"
displayName="Cable Tiers"
displayURL="https://www.curseforge.com/minecraft/mc-mods/cable-tiers"
logoFile="logo.png"
credits="Thanks for downloading this mod."
authors="YTrollman"
description="This mod adds Tiered RS Things."

[[dependencies.cabletiers]]
    modId="refinedstorage"
    mandatory=true
    versionRange="[1.10.0-beta.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cabletiers]]
    modId="forge"
    mandatory=true
    versionRange="[39.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cabletiers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"
